# Site settings
title: "Mainliufeng's Blog" 
header-img: img/home-bg.jpg
email: mainliufeng@gmail.com
description: "Mainliufeng's Blog"
# baseurl: "/Blog"
# url: "http://yourdomain.com"
twitter_username: mainliufeng 
github_username: "Liu-Feng" 
facebook_username: mainliufeng 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
